-- AlterTable
ALTER TABLE `user` ADD COLUMN `meetId` VARCHAR(191) NULL,
    MODIFY `age` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `refresh` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `callsNumber` INTEGER NOT NULL DEFAULT 0;

-- CreateTable
CREATE TABLE `Meet` (
    `id` VARCHAR(191) NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `User` ADD CONSTRAINT `User_meetId_fkey` FOREIGN KEY (`meetId`) REFERENCES `Meet`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
